# Usar la imagen base oficial de Alpine Linux
FROM alpine:latest

# Añadir un mensaje de bienvenida
RUN echo "¡Hola, Docker!" > /mensaje.txt

# Comando que se ejecutará cuando se inicie el contenedor
CMD ["cat", "/mensaje.txt"]
